### ISSUE TITLE
[Properties] Best way to name properties 

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/element#150]
my personal favourite is how we do it atm
```javascript
{
  text: ,
  css: 
  // etc
}
```

however as was mentioned in the state issue this may not be clear lets decide ones and for all!

in general to much prefixing does not help the readability (thats what we saw when we prefixed everything with a `$`) 

now the only things prefixed with `$` are operators and as a decision within a subscription object
$parent and $root

another option what we can do is make an extra field (like reacts properties field) however keep in mind that it does not necessarily makes it more readable and adds more code 

http://staltz.com/why-react-redux-is-an-inferior-paradigm.html
good read concerning front-end framework design

@nikoloza , @nfrade, @youzi

**Comment by youzi** [comment]
I like how we currently do properties (short and sweet). However I can imagine for someone external it might be more intuitive if properties are closer to css style properties. Another thing is prefixing, which I personally think is horrible.

For your consideration:
```js
var elem = e({
  tagName:'DIV',
  textNode:'Hello World',
  className: 'magical-class',
  translate3d:{
    x:10,
    y:30,
    z:40
  },
  width:100,
  height:20,
})
```

```js
var elem = e({
  type:'div',
  text:'Hello World',
  css: 'magical-class',
  x:10,
  y:30,
  z:40,
  w:100,
  h:20,
})
```

```js
var elem = e({
  $tagName:'DIV',
  $textNode:'Hello World',
  $className: 'magical-class',
  $translate3d:{
    x:10,
    y:30,
    z:40
  },
  $width:100,
  $height:20,
})
```

```js
var elem = e({
  $type:'div',
  $text:'Hello World',
  $css: 'magical-class',
  $x:10,
  $y:30,
  $z:40,
  $w:100,
  $h:20,
})
```

**Comment by jimdebeer** [comment]
I really like the idea to stick to normal dom-elements very smart! style: {} could be a thing

**Comment by youzi** [comment]
```js
var elem = e({
  tagName:'DIV',
  textNode:'Hello World',
  className: 'magical-class',
  style:{
    translate3d:{
      x:10,
      y:30,
      z:40
    },
    width:100,
    height:20
  },
  randomChild:{},
  anotherChild:{}
})
```
vs
```js
var elem = e({
  tagName:'DIV',
  textNode:'Hello World',
  className: 'magical-class',
  translate3d:{
    x:10,
    y:30,
    z:40
  },
  width:100,
  height:20,
  randomChild:{},
  anotherChild:{}
})
```

**Comment by nfrade** [comment]
You guys are right. Namespacing everything does look uglier :\
Can we have a warning when we use a "reserved" word? Maybe at bundle/compile time?

I like the idea of css properties being grouped by style.

**Comment by nikoloza** [comment]
+1 @nfrade, style wrapper for css things. If we use native naming like `tagName`, `textNode` we don't need `$` I think. otherwise, `$` is good to differ what is framework related and what's not. Also, as @nfrade mentioned, if we throw an error for reserved words, that'll also work, and avoids $ and other extra prefixes.

**Comment by youzi** [comment]
```js
var elem = e({
  props:{
    tagName:'DIV',
    textNode:'Hello World',
    className: 'magical-class'
  },
  style:{
    translate3d:{
      x:10,
      y:30,
      z:40
    },
    width:100,
    height:20
  },
  randomChild:{},
  anotherChild:{}
})
```
vs
```js
var elem = e({
  attr:{
    tagName:'DIV',
    textNode:'Hello World',
    className: 'magical-class'
  },
  style:{
    translate3d:{
      x:10,
      y:30,
      z:40
    },
    width:100,
    height:20
  },
  randomChild:{},
  anotherChild:{}
})
```
/cc @vigour-io/front-end

**Comment by jimdebeer** [comment]
i like the option but i would like to add a few properties



text, css, node <--- have these on the top level rest just goes in props and style
reason -- text is special, node and css are used all the itme

**Comment by jimdebeer** [comment]
error for for example text is a bit harsh -- since it really is not an error same for css, same for node -- if we log this you flood your logs completely

**Comment by jimdebeer** [comment]
also the text exclusion and css is very simmialir to h-script and react -- difference is css is called `class`

**Comment by jimdebeer** [comment]
it is now props and style, text, class, node are the exceptions that are still on top level
