### ISSUE TITLE
[Refactor/State] Events

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/element#156]
- [x] investigate if we need dom delegator or can just not use it
- [x] mind node.js  (!)
- [x] check if storing a handle on the dom node is faster
- [ ] cases how to deal with this?
- [ ] make it!
- [x] states -- can also store straight on the state tree if you want that little extra speed -- this is not perfect though -- but faster

**Comment by youzi** [comment]
Prefer to use dom delegator (at first). This will safe us some time.

**Comment by youzi** [comment]
We can do something special for "hot events" like move and scroll. Something like:
```js
// for eg. scroll event
// on creation => if not in cache create global event + store ref to interested node somewhere
// on first tick of scroll event, check if all stored "interested nodes" are still in the dom
// if yes => proceed normally
// if no => remove the global event, until it's added again (on render)
```
Another option is to use event listeners (not global), for scroll and move.

**Comment by youzi** [comment]
Are passing the state object to events? Would be nice.
Let's see if we need a special syntax to indicate if we are interested in data on an event.

**Comment by youzi** [comment]
Consider the current situation:
We have currently  have `down` as a polyfill for down events (`touchstart` and `mousedown`). When we have a touch enabled device we map `down` to `touchstart`. This is not always correct (on Surface eg). Should we listen for both mouse events + touch events?

**Comment by youzi** [comment]
Check with @vigour-io/native if we can block body scroll on iOS.

**Comment by youzi** [comment]
- [ ] drag
- [ ] grab
- [ ] right click
- [ ] 3d touch (ios)
- [ ] scroll
- [ ] x and y values

**Comment by youzi** [comment]
Example event data for drag:
![image](https://cloud.githubusercontent.com/assets/5662898/14979436/89ee1e58-1122-11e6-9e7e-fb2978fd8701.png)
/cc @vigour-io/front-end @jimdebeer

**Comment by youzi** [comment]
Think **right click** should be:
- right click on mouse
- tap and hold on touch

/cc @vigour-io/front-end

**Comment by youzi** [comment]
Force touch docs: https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/SafariJSProgTopics/RespondingtoForceTouchEventsfromJavaScript.html#//apple_ref/doc/uid/TP40016162

**Comment by youzi** [comment]
**TODO** remove listeners when a fire fails (fire fails when an element is set to display none or is removed)

**Comment by youzi** [comment]
- [ ] Adding key events

**Comment by youzi** [comment]
Will add custom click, when we get more complex examples going. Closing.
