### ISSUE TITLE
[Refactor/State] Operators

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/element#157]
- [ ] Object operator (in observable) 
- [ ] faster keys (props optimisations etc) see https://github.com/vigour-io/observable/issues/46
- [ ] Operator subscription
- [ ] Cases
- [ ] Subscribe operator support (condition)

**Comment by jimdebeer** [comment]
can use $switch

**Comment by youzi** [comment]
**Subscribe in value operators:**
Need to be able to pass state only to operator, while using static on value itself
