### ISSUE TITLE
[Refactor/State] Subscribe

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/element#158]
- [x] ~~~multiple objects~~~ -- dont do this for now
- [x] option for traveler subscribers to use `$done` (for property group)
- [x] condition (as mentioned #157) <--- later
- [x] $: true to force adherence to tree ? (this is now by default)
- [x] map does not work well with nested fields (allways from root)
- [x] fix the $any subscription, since its ugly
- [x] clean up the map file -- its very dirty atm
- [x] ~~defaultSubs make it nicer (e.g. add the object in there!)~~
- [x] ~~make $ an observable (so it calls clearKeys) <--- later (when combined with operators)~~~
- [x] write the val to an array (stored in _$path)
- [x] fix the isNoState check -- very slow -- need to do addSubscriber after iterator
- [x] remove add
- [x] add set method for paths
- [x] split up in switcher, collection, normal, traveler, iterator
- [x] move subscribe to end
- [x] make $collection like $switch
- [x] clear isSwitcher and isCollection
- [x] $: true should make traveler / def subs (for text for example)
- [x] only store array on `this.$`
- [x] re-enable collection
- [x] re-enable switch
- [x] optimise t and s list -- if there is no t just use the sList (better) -- check if there is extra time
- [x] make tests for merge subs -- and think about it seems flimsy now
- [x] properties always get the pid from the first element you can find

```
    $any: true, // unify and make easier
    $: 'collection'
```

**Comment by jimdebeer** [comment]
map problem -- travelers need to go one map up -- non travelers need to go one map down

**Comment by jimdebeer** [comment]
like ` $: '$any.collection'` ?

**Comment by jimdebeer** [comment]
-- also default is nice to put in here

**Comment by jimdebeer** [comment]
subs need to be an observalbe (compute for the map)

**Comment by youzi** [comment]
**cleanup**
- [ ] move subscribe to end
- [ ] make $collection like $switch
- [ ] clear isSwitcher and isCollection
- [ ] $: true should make traveler
