### ISSUE TITLE
[Refactor/State] Hscript

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/element#163]
- [ ] cleanup property (dom methods)
- [x] add dom render type
- [x] create a type for render/index
- [ ] add hscript first -- gets a tree similair to dom -- pretty nice
- [x] ~~straight html (?) low priority leave it for now~~~

**Comment by jimdebeer** [comment]
try to dable with canvas as well ( this is for later)

**Comment by jimdebeer** [comment]
need to fire updates since we want to update a cached string for example every time it fires

**Comment by jimdebeer** [comment]
solution for different engines
```
{
  class: {
   render: { DOM: , canvas, hscript, html, x/y/z }
  }
}
```

**Comment by jimdebeer** [comment]
class will be hardest for tvos -- canvas engines -- but may pose a very nice challenge for someone in team native

**Comment by jimdebeer** [comment]
need to inject everything except dom on init -- i suppose

**Comment by youzi** [comment]
We now have node rendering by using [html-element](https://github.com/1N50MN14/html-element) no need for hscript!
