### ISSUE TITLE
[cases] Cases does not apply text changes on body

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/element#171]
when looking on this file: https://github.com/vigour-io/play-rtl/blob/0e7728b6d6853de81ee44617346accbb007656e5/test/index.js#L11-L20, text change on button works, but not on body.

**Comment by jimdebeer** [comment]
just use cases on props only for now

**Comment by nikoloza** [comment]
@jimdebeer text is also property 💃

**Comment by jimdebeer** [comment]
yeah but using it in the property not on the element

```javascript
$case: {
  text: 'xxx'
}
```

vs

```javascript
text: { $case: 'xxx' }
```

**Comment by jimdebeer** [comment]
use it **inside** the property
