### ISSUE TITLE
[Refactor/State] Order

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/element#177]
- [x] counter (incrementing)
- [x] may need to change base for subscriptions orders
- [x] keys adjustment
- [x] satic data-order only necessary when no state things are lower then state
    -- e.g. the collection example
- [x] state order -- no context linked list
- [x] state order - state context linked list
- [x] context order -- when adding the subscriber don't have information about isStatic for children
   --- this is a problem!
- [x] test isStatic: 1 -- this may fuck up everything!
- [x] findNode fix it

**Comment by youzi** [comment]
Implemented. Need to test some more before closing this.

**Comment by youzi** [comment]
doesnt work

**Comment by jimdebeer** [comment]
not ready
