### ISSUE TITLE
[Keys] State argument for keys/order

### ISSUE THREAD

**Issue by youzi** [vigour-io/element#180]
This allows use to key sorting based on state/data (ie with order).

Keys would have to be passed state if available, which isn't very nice.

Keys are used in each etc. so need to take care of that.

Option for not extending .keys(), would be to clearKeys on state update, create a "keys cache" which is what the original .keys() would return.

**Comment by jimdebeer** [comment]
probably have to add some stuff to base -- seems a pretty common usecase

**Comment by jimdebeer** [comment]
after 6th of june
