### ISSUE TITLE
[Player] player plugin system

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/element#54]
we need a video player plugin system

we need a html5 video player 

check this stuff in vigour-js/browser/element/video

**Comment by ricksmitvigour** [comment]
~~ :sparkles: :sparkles: Abstraction layer :sparkles: :sparkles: ~~ 
Player is vObj, properties are also vObj's
Use as little from the API's as possible

Events:
- [ ] Play
- [ ] Pause
- [ ] Play from certain time
- [ ] Toggle fullscreen
- [ ] Seek
- [ ] Progress 
- [ ] Duration
- [ ] Current time
- [ ] Set new video src
