### ISSUE TITLE
[Event] window.onresize event is needed

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/element#57]
We'll need `resize` event handler for `app` object.

**Comment by renancarvalho** [comment]
@nikoloza can you explain me this ?

**Comment by nikoloza** [comment]
@renancarvalho it's about to detect correct `app.width` and `app.height` anytime you want (even after window resizing).

It's something like `window.AddEventListener('resize', ...)`, but it must also update our properties to keep them up-to-date
