### ISSUE TITLE
[Cleanup] Remove unused examples 

### ISSUE THREAD

**Issue by youzi** [vigour-io/element#78]
We currently have a lot of examples, please take a moment to indicate which ones you are using:
- [ ] animnew
- [ ] animnewoperator
- [x] app
- [x] background
- [x] background-image
- [ ] bitdash
- [x] cases
- [x] coke
- [x] css-animations
- [x] dictionary
- [x] drag
- [ ] drag-old
- [ ] events
- [ ] gaston-less-options
- [x] js-animation
- [ ] jsdom
- [x] player
- [ ] posts
- [x] properties
- [x] property
- [ ] random-example
- [ ] remove
- [x] scroll
- [ ] scroll2
- [x] snake
- [ ] stringparser
- [x] style
- [x] subcribe
- [ ] transforms

@vigour-io/ui

**Comment by nikoloza** [comment]
I really like to use them, but most of them are broken by now.

**Comment by youzi** [comment]
Unchecked items have been removed. Closing.
